"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var FileHandler_1 = require("../helpers/FileHandler");
var dynatrace_config_template_1 = require("../config-files-template/ConcreteFilesTemplate/dynatrace.config.template");
var metro_config_template_1 = require("../config-files-template/ConcreteFilesTemplate/metro.config.template");
var configsObject = require("../../../../dynatrace-destination.config");
var fileHandler = new FileHandler_1.FileHandler();
var dynatraceConfigTemplate = new dynatrace_config_template_1.DynatraceConfigTemplate(configsObject);
var metroConfigTemplate = new metro_config_template_1.MetroConfigTemplate();
fileHandler.writeFile("../../../../dynatrace.config.js", dynatraceConfigTemplate);
fileHandler.writeFile("../../../../metro.config.js", metroConfigTemplate);
